services:
  - type: web
    name: pdf-server
    runtime: node
    plan: free
    buildCommand: npm install --production --omit=optional
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://qgen-mu.vercel.app
      - key: PUPPETEER_HEADLESS
        value: "true"
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_ARGS
        value: --no-sandbox,--disable-setuid-sandbox
